environment:

  TOX_ENV: pywin

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: 2.7.8
      PYTHON_ARCH: 32

build: false

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - ps: (new-object System.Net.WebClient).Downloadfile('https://bootstrap.pypa.io/get-pip.py', 'C:\Users\appveyor\get-pip.py')
  - ps: Start-Process -FilePath "C:\Python27\python.exe" -ArgumentList "C:\Users\appveyor\get-pip.py" -Wait -Passthru

before_test:
  - pip install virtualenv --upgrade
  - virtualenv env
  - 'env\Scripts\activate.bat'
  - pip install tox

test_script:
  - pip --version
  - tox --version
  - tox -e %TOX_ENV%
